name = "m3u-token-secure"
type = "javascript"

[build]
  command = "npm install"

[env.production]
  workers_dev = true

[account]
  id = "a25472f8446d3aa3646070265fa5d6a60d9cd"

[env.staging]
  workers_dev = false
